version: '3.7'

x-app-defaults: &app_defaults
  image: node:14
  volumes:
    - ./:/usr/src/service/
  working_dir: /usr/src/service/
  environment:
    NODE_ENV: "${NODE_ENV:-production}"
    DATABASE_HOST: db
    DATABASE_PORT: 5432
    DATABASE_NAME: features
    DATABASE_USERNAME: features
    DATABASE_PASSWORD: features
    DATABASE_SCHEMA: public
    JWT_SECRET: secretKey
    JWT_EXPIRES_IN: 12h
    CLIENT_URL: http://localhost:3000

services:
  app-install:
    << : *app_defaults
    command: bash -c "yarn install"

  app-build:
    << : *app_defaults
    command:  bash -c "rm -rf dist && yarn build"

  app-start:
    << : *app_defaults
    depends_on:
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/start.sh"
    ports:
      - "3000:3000"

  app-migrate:
    << : *app_defaults
    depends_on:
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/migrate.sh"

  app-fixture:
    << : *app_defaults
    depends_on:
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/fixture.sh"

  app-dev:
    << : *app_defaults
    depends_on:
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- yarn start:dev"
    ports:
      - "3000:3000"

  db:
    image: postgres
    container_name: "${DB_CONTAINER:-feature_service_db_container}"
    depends_on:
    environment:
      POSTGRES_USER: features
      POSTGRES_PASSWORD: features
      POSTGRES_DB: features
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - feature-db:/var/lib/postgresql/data

volumes:
  feature-db:
    name: "${DB_VOLUME:-feature_service_db_volume}"
