version: '3.7'

x-app-defaults: &app_defaults
  image: node:14
  volumes:
    - ./:/usr/src/service/
  working_dir: /usr/src/service/
  environment:
    NODE_ENV: "${NODE_ENV:-production}"
    DATABASE_HOST: db
    DATABASE_PORT: 5432
    DATABASE_NAME: features
    DATABASE_USERNAME: features
    DATABASE_PASSWORD: features
    DATABASE_SCHEMA: public
    ETCD_HOSTS: "[\"http://etcd0:2379\"]"
    ETCD_NAMESPACE: featurist/
    JWT_SECRET: secretKey
    JWT_EXPIRES_IN: 12h
    CLIENT_URL: http://localhost:3000

services:
  app-install:
    << : *app_defaults
    command: bash -c "yarn install"

  app-build:
    << : *app_defaults
    command:  bash -c "rm -rf dist && yarn build"

  app-start:
    << : *app_defaults
    depends_on:
      - etcd0
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/start.sh"
    ports:
      - "3000:3000"

  app-migrate:
    << : *app_defaults
    depends_on:
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/migrate.sh"

  app-fixture:
    << : *app_defaults
    depends_on:
      - etcd0
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- ./deploy/scripts/fixture.sh"

  app-dev:
    << : *app_defaults
    depends_on:
      - etcd0
      - db
    command: bash -c "third_party/wait-for-it.sh db:5432 -- yarn start:dev"
    ports:
      - "3000:3000"

  etcd0:
    image: quay.io/coreos/etcd:v3.3.25
    container_name: "${ETCD_CONTAINER:-feature_service_etcd_container}"
    command:
      - /usr/local/bin/etcd
      -  --name
      - etcd0
      - --data-dir
      - /etcd-data
      - --advertise-client-urls
      - http://etcd0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      -  --initial-advertise-peer-urls
      - http://etcd0:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - etcd0=http://etcd0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data

  db:
    image: postgres
    container_name: "${DB_CONTAINER:-feature_service_db_container}"
    depends_on:
      - etcd0
    environment:
      POSTGRES_USER: features
      POSTGRES_PASSWORD: features
      POSTGRES_DB: features
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - strapi-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@payday.ru
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
      - ./develop/pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin:/var/lib/pgadmin

volumes:
  etcd-data:
    name: "${ETCD_VOLUME:-feature_service_etcd_volume}"
  strapi-db:
    name: "${DB_VOLUME:-feature_service_db_volume}"
  pgadmin:
    name: "${PGADMIN_VOLUME:-feaute_service_pgadmin_volume}"
