name: build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Run unit tests
      run: |
        yarn install --frozen-lockfile
        yarn test:cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Setup application
      run: |
        make start
        ./third_party/wait-for-it.sh 0.0.0.0:3000
    - name: Run e2e tests
      run: |
        yarn install --frozen-lockfile
        yarn test:e2e
