name: build

on: [ push, pull_request ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Run unit tests
      run: |
        yarn test:cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Setup environment
      run: |
        make start-detached
        ./third_party/wait-for-it.sh 0.0.0.0:3000

    - name: Run e2e tests
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: 6000
        DATABASE_NAME: features
        DATABASE_USERNAME: features
        DATABASE_PASSWORD: features
        DATABASE_SCHEMA: public
        TZ: Etc/UTC
      run: |
        yarn test:e2e

  openapi-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Setup environment
      run: |
        make start-detached
        ./third_party/wait-for-it.sh 0.0.0.0:3000

    - name: Run openapi tests
      run: |
        yarn test:openapi
